# Generated by Django 3.2.6 on 2021-08-15 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.CharField(db_index=True, max_length=30, verbose_name='사건명')),
                ('photo', models.ImageField(upload_to='', verbose_name='사진')),
                ('time', models.CharField(db_index=True, max_length=10, verbose_name='발견 시간')),
                ('area', models.CharField(db_index=True, max_length=30, verbose_name='지역')),
                ('desc', models.TextField(verbose_name='설명')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Timetravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.CharField(db_index=True, max_length=30, verbose_name='사건명')),
                ('photo', models.ImageField(upload_to='', verbose_name='사진')),
                ('time', models.CharField(db_index=True, max_length=10, verbose_name='발견 시간')),
                ('area', models.CharField(db_index=True, max_length=30, verbose_name='지역')),
                ('desc', models.TextField(verbose_name='설명')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ufo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.CharField(db_index=True, max_length=30, verbose_name='사건명')),
                ('photo', models.ImageField(upload_to='', verbose_name='사진')),
                ('time', models.CharField(db_index=True, max_length=10, verbose_name='발견 시간')),
                ('area', models.CharField(db_index=True, max_length=30, verbose_name='지역')),
                ('desc', models.TextField(verbose_name='설명')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('youtube_url', models.URLField()),
                ('Timretravel_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystery.timetravel')),
                ('creature_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystery.creature')),
                ('ufo_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystery.ufo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('Timretravel_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystery.timetravel')),
                ('creature_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystery.creature')),
                ('ufo_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystery.ufo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
